// Curated slogan packs for the bulk generator. All original wording — no
// trademarks, no copyrighted phrases, no celebrity/brand references. Picked
// to bias toward proven-selling Etsy t-shirt niches.

export type Theme = {
  slug: string;
  label: string;
  emoji: string;
  description: string;
  slogans: string[];
};

export const THEMES: Theme[] = [
  {
    slug: 'mom-life',
    label: 'Mom Life',
    emoji: '🤱',
    description: 'Funny and tender slogans for moms.',
    slogans: [
      'Snack Provider. Threat Manager. Mom.',
      'Mom Brain. Loading… Please Wait.',
      'I Run on Coffee, Chaos, and Cuddles.',
      'Currently Outnumbered by Tiny Humans.',
      'Tired as a Mother.',
      'World\'s Okayest Mom.',
      'Hot Mess Express, Mom Edition.',
      'My Kids\' Snack Bitch.',
      'Mama Bear with a Caffeine Problem.',
      'Raising Future Adults Is Wild.',
      'Mom Hair, Don\'t Care.',
      'I Birthed These Tiny Critics.',
      'Just a Mom Trying Her Best.',
      'Mom of the Year, Probably.',
      'Powered by Tantrums and Iced Coffee.',
      'Cool Mom in Training.',
      'Boys Mom, Send Help and Pizza.',
      'Girl Mom, Pray For Me.',
      'Soccer Mom Energy, All Day.',
      'I Have Snack Rage.',
      'Promoted to Mommy, est. [your year].',
      'My Patience Is on Backorder.',
      'Mama Don\'t Play.',
      'Wine Mom Vibes.',
      'I Made These Tiny Humans.',
    ],
  },
  {
    slug: 'cat-lover',
    label: 'Cat Lover',
    emoji: '🐱',
    description: 'For the cat people who already have nine.',
    slogans: [
      'Sorry I\'m Late. My Cat Was Sitting on Me.',
      'My Cat Is My Therapist.',
      'Crazy Cat Lady in Training.',
      'I Just Want to Pet All the Cats.',
      'Cats Are Just Tiny Roommates Who Don\'t Pay Rent.',
      'I Work Hard So My Cat Can Live a Better Life.',
      'My Cat Brings Me Dead Things and I\'m Grateful.',
      'Excuse Me, I Have a Cat to Get Back To.',
      'Less People. More Cats.',
      'Cat Hair Is My Glitter.',
      'I\'m the Crazy Cat Aunt.',
      'My Cat Walked on My Keyboard.',
      'Talk Cats To Me.',
      'Adopt, Don\'t Shop.',
      'Local Cat Distribution System.',
      'In My Defense, the Cat Looked Lonely.',
      'I Have Cats Therefore I Am.',
      'Cat Mom Era.',
      'I Speak Fluent Meow.',
      'You Had Me at Meow.',
      'The Cat Is in Charge Here.',
      'Coffee, Cats, and Chaos.',
      'I\'m Just Here for the Cats.',
      'I Identify as a Cat Person.',
      'Send Help. Or Cats.',
    ],
  },
  {
    slug: 'dog-lover',
    label: 'Dog Lover',
    emoji: '🐶',
    description: 'For dog parents who introduce their dog first.',
    slogans: [
      'I Just Want to Pet All the Dogs.',
      'Dog Hair, Don\'t Care.',
      'My Therapist Has Four Paws.',
      'My Dog Is My Co-Pilot.',
      'Dogs Are the Reason I Get Up in the Morning.',
      'Sorry I\'m Late, My Dog Wanted Snuggles.',
      'I Work So My Dog Can Have a Better Life.',
      'Dog Mom and Proud.',
      'Dog Dad Energy.',
      'Less Monday, More Doggy.',
      'My Dog Thinks I\'m Cool.',
      'Talk Dogs To Me.',
      'A House Is Not a Home Without a Dog.',
      'I Just Want to Cuddle My Dog.',
      'My Dog Picked This Shirt.',
      'You Had Me at Woof.',
      'Adopted. Not Bought.',
      'My Family Has Paws.',
      'Powered by Coffee and Dog Slobber.',
      'I Stop for Dogs.',
      'Excuse the Dog Hair on Everything.',
      'I Love Dogs and Like Three People.',
      'Dog Walker, Treat Dispenser, Best Friend.',
      'I Brake for Dogs.',
      'My Dog Is My Whole Personality.',
    ],
  },
  {
    slug: 'anxiety-humor',
    label: 'Anxiety Humor',
    emoji: '😬',
    description: 'Mental health-aware humor that resonates.',
    slogans: [
      'I Came. I Saw. I Made It Awkward.',
      'Socially Distancing Since Forever.',
      'Anxiety Has Entered the Chat.',
      'On My Worst Behavior. Internally.',
      'Mentally on a Beach. Physically Here.',
      'Functioning at Maybe 60%.',
      'I\'m Fine. Probably.',
      'Introvert in Training.',
      'I Have Too Many Tabs Open in My Brain.',
      'Catch Me Overthinking This Shirt.',
      'Sorry I\'m Late. I Didn\'t Want to Come.',
      'Trust Issues, Charmingly.',
      'Resting Anxious Face.',
      'I Brought My Anxiety Today.',
      'Plot Twist: I\'m Tired Again.',
      'Send Memes, Not Plans.',
      'Pretending to Have It Together.',
      'Overthinking Is My Cardio.',
      'My Brain Has Too Many Tabs Open.',
      'Internally Screaming. Externally Smiling.',
      'I\'m an Introvert. I\'m Fully Charged Now Leave.',
      'My Battery Is at 12%.',
      'Cancel My Plans, I\'m Tired.',
      'Worry First, Cope Later.',
      'I Have Social Battery Issues.',
    ],
  },
  {
    slug: 'sarcasm',
    label: 'Sarcasm',
    emoji: '🙃',
    description: 'Dry, snarky, deadpan.',
    slogans: [
      'I Tried to Be Normal. Once. Worst Two Minutes Ever.',
      'I\'m Not Arguing, I\'m Just Explaining Why I\'m Right.',
      'My Patience Has Left the Group Chat.',
      'I Have a Plan: It\'s a Bad One.',
      'Mildly Annoyed, Always.',
      'I\'m Sorry. Did the Middle of My Sentence Interrupt You?',
      'Listening Is Hard.',
      'I Run on Spite.',
      'Professional Eye-Roller.',
      'I\'m Not Bossy. I Just Have Better Ideas.',
      'Allergic to Stupidity.',
      'Adulting Today: Canceled.',
      'I Don\'t Need Therapy. I Need Snacks.',
      'Resting Witch Face.',
      'I Could Be Wrong But I\'m Not.',
      'Be the Reason Someone Believes in Snark.',
      'I Came Here to Be Petty.',
      'I\'m Not Yelling. This Is My Inside Voice.',
      'Sarcasm Is My Love Language.',
      'I\'d Agree With You But Then We\'d Both Be Wrong.',
      'Trust Me, I\'m a Professional Disappointment.',
      'My Last Brain Cell Quit.',
      'I Have a Master\'s in Side-Eye.',
      'Common Sense Is a Flower That Doesn\'t Grow in Everyone\'s Garden.',
      'I\'m Not Rude. You\'re Just Soft.',
    ],
  },
  {
    slug: 'plant-lady',
    label: 'Plant Lady',
    emoji: '🪴',
    description: 'For people who buy a new pothos every weekend.',
    slogans: [
      'Plant Mom Era.',
      'Crazy Plant Lady.',
      'I Speak Fluent Houseplant.',
      'One More Plant Won\'t Hurt.',
      'My Plants Are My Children.',
      'Sorry I\'m Late. I Was Repotting.',
      'Talk Plants to Me.',
      'You Can Never Have Too Many Plants.',
      'A House Without Plants Is Just a Building.',
      'I Have a Green Thumb and Trust Issues.',
      'Plants Don\'t Talk Back.',
      'Just a Girl Standing in Front of a Plant Asking It to Live.',
      'Don\'t Get High. Get Plants.',
      'Powered by Sunlight and Coffee.',
      'I Like Big Pots and I Cannot Lie.',
      'Help, I\'ve Bought More Plants Than I Have Space For.',
      'Local Plant Hoarder.',
      'Plant Hoarder. Proud.',
      'Plant Therapy Beats Talk Therapy.',
      'My Hobby Is Killing Plants. And Buying More.',
      'Garden Variety Mess.',
      'Stay Wild, Stay Watered.',
      'My Plants Are My Personality.',
      'In a Relationship With My Plants.',
      'Will Trade Husband for Plants.',
    ],
  },
  {
    slug: 'coffee-addict',
    label: 'Coffee Addict',
    emoji: '☕',
    description: 'Iced, hot, doesn\'t matter — just hand it over.',
    slogans: [
      'But First, Coffee.',
      'Coffee, Then Conversation.',
      'Powered by Coffee and Spite.',
      'Don\'t Talk to Me Until I\'ve Had Coffee.',
      'I Run on Coffee and Bad Decisions.',
      'Coffee Is My Love Language.',
      'Decaf Is for the Weak.',
      'Insert Coffee to Begin.',
      'I\'m Not a Morning Person. I\'m a Coffee Person.',
      'Coffee Hair, Don\'t Care.',
      'My Blood Type Is Espresso.',
      'I Need Coffee in an IV.',
      'Coffee First. Adulting Second.',
      'Iced Coffee in My Veins.',
      'Tell Me a Secret. Tell Me Coffee Is Ready.',
      'Coffee Is Cheaper Than Therapy.',
      'Espresso Yourself.',
      'Procaffeinating: The Tendency to Not Start Anything Until You\'ve Had Coffee.',
      'Caffeine Queen.',
      'Caffeine and Chaos.',
      'I Like My Coffee Like I Like My Mornings: Strong and Black.',
      'Latte Today. Cappuccino Tomorrow.',
      'Coffee Solves Almost Everything.',
      'Resting Coffee Face.',
      'World\'s Okayest Barista (in My Kitchen).',
    ],
  },
  {
    slug: 'teacher-life',
    label: 'Teacher Life',
    emoji: '🍎',
    description: 'For the educators surviving on coffee and snacks.',
    slogans: [
      'Teacher: Because Miracle Worker Wasn\'t a Job Title.',
      'I Teach. What\'s Your Superpower?',
      'Powered by Coffee and Crayons.',
      'Teaching Is My Jam.',
      'Tired Teacher. Caffeinated. Persistent.',
      'I Teach Tiny Humans.',
      'Patience Loading…',
      'It\'s a Good Day to Have a Good Day.',
      'I Teach. I Inspire. I Survive.',
      'Sorry I\'m Late. School Stuff.',
      'Just Counting Down to the Bell.',
      'Teach. Sleep. Repeat.',
      'Coffee. Crayons. Chaos.',
      'World\'s Okayest Teacher.',
      'I\'m a Teacher. What\'s Your Excuse?',
      'My Class Is Bananas.',
      'Be Kind. Work Hard. Eat Snacks.',
      'I Teach the Cutest Kids in the World.',
      'I Survived Another School Year.',
      'Kindergarten Cool.',
      'Math Teacher: Where\'s the Pencil You Borrowed Three Years Ago?',
      'Science Teacher: I Have All the Solutions.',
      'I Teach Therefore I Drink Coffee.',
      'Recess Counselor.',
      'Substitute Teacher: Hold My Coffee.',
    ],
  },
];

export function findTheme(slug: string): Theme | undefined {
  return THEMES.find((t) => t.slug === slug);
}
